name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          envkey_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          file_name: .env

      - name: Verify envfile
        run: |
          TEST=$(cat .env)
          echo "$TEST"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.20.0

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.5.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --shamefully-hoist

      - name: Run Lint
        run: pnpm run lint

      - name: Run Build
        run: pnpm run build
